### ISSUE TITLE
consider the inclusion of unit tests using the `testthat` framework

### ISSUE THREAD

**Issue by schifferl** [waldronlab/GSEABenchmarkeR#2]
Unit tests can be constructed and run using the `testthat` framework and automated via Travis-CI and AppVeyor. Happy to set it up if you want me to.

**Comment by lgeistlinger** [comment]
Hm, would be great I guess - are these tests part of R CMD check?
(as there is the 5 min limit ...)

**Comment by schifferl** [comment]
The test do happen as part of `R CMD check` and are usually fast, but packages with data can be tough sometimes. If you want to use unit test just tell me and I will add the `testthat` framework to the package.

**Comment by lgeistlinger** [comment]
Yes, let's do it - I would definitely be able to populate it with some lightweight tests that do not draw too much on the check time.

**Comment by schifferl** [comment]
Closed via c945214. Look at the example test in the `tests/testthat` directory and add unit tests as necessary.
