### ISSUE TITLE
consider moving data files to the data directory

### ISSUE THREAD

**Issue by schifferl** [waldronlab/GSEABenchmarkeR#3]
Moving files used in benchmarking to the `data` directory and saving them as `.Rda` files will provide a greater degree of transparency for users and expose the data used in the package for inspection.

**Comment by lgeistlinger** [comment]
Are you referring to the files in `inst/extdata`?

**Comment by schifferl** [comment]
I am referring to those files in `inst/extdata` but I know you have used `BiocFileCache` (I know nothing about it beyond that it is awesome) so perhaps my suggestion is moot.

**Comment by lgeistlinger** [comment]
Guess that's fine then - all relevant files are in the `extdata` folder.
Functionality of `BiocFileCache` is currently only incorporated the `EnrichmentBrowser` - not here.
Thanks!
