### ISSUE TITLE
upgrade to R dependency to version >=3.5.0 prior to submission to Bioconductor

### ISSUE THREAD

**Issue by schifferl** [waldronlab/GSEABenchmarkeR#4]
Submission to Bioc-devel will require the use of R version >=3.5.0 – this should be updated in the `DESCRIPTION` file prior to submission. Yet, be warned that updating may break things and will require all `Depends`, `Imports`, and `Suggests` packages to be installed again.

**Comment by lgeistlinger** [comment]
Accordingly adapted. Thanks!
