### ISSUE TITLE
Including other enrichment analysis methods

### ISSUE THREAD

**Issue by moldach** [waldronlab/GSEABenchmarkeR#6]
From the Vignette it's clear that one can add user-defined data compendium's. However, it's not clear if one can include their own enrichment analysis methods into the benchmarking workflow or if you are restricted to the set-based and network-based methods from the `EnrichmentBrowser`?

```
library(EnrichmentBrowser)
sbeaMethods()
 [1] "ora"        "safe"       "gsea"       "gsa"        "padog"      "globaltest" "roast"      "camera"     "gsva"       "samgs"     
[11] "ebm"        "mgsa" 
nbeaMethods()
[1] "ggea"        "spia"        "pathnet"     "degraph"    
[5] "ganpa"       "cepa"        "topologygsa" "netgsa" 
```
This would be a useful as novel methods are developed

**Comment by lgeistlinger** [comment]
Thanks. Adding on that in the vignette.

`GSEABenchmarkeR::runEA` passes execution of individual methods on to `EnrichmentBrowser::sbea` and `EnrichmentBrowser::nbea`, both accepting user-defined methods as detailed and exemplified in their corresponding example sections.

I've never tested it above these two dummy examples, i.e. happy to look into it as soon as you a have a specific use case.

**Comment by lgeistlinger** [comment]
This is now documented in 
- Supplementary Methods S1.7 _Benchmarking user-defined methods_ of the paper (https://doi.org/10.1093/bib/bbz158)
- Vignette, Section 5.1 _User-defined methods_ https://github.com/waldronlab/GSEABenchmarkeR/blob/6fc06db6f1ed37f2b254ebd3726f4467d9fd9ae6/vignettes/GSEABenchmarkeR.Rmd#L350 
- The `examples` section of `runEA`  https://github.com/waldronlab/GSEABenchmarkeR/blob/6fc06db6f1ed37f2b254ebd3726f4467d9fd9ae6/R/ea.R#L236
