### ISSUE TITLE
Functional enrichment of differentially methylated regions (DMRs)

### ISSUE THREAD

**Issue by moldach** [waldronlab/GSEABenchmarkeR#7]
I need to do some functional enrichment of differentially methylated regions (DMRs). 

It's my understanding that typically one maps the probe ID of each differentially methylated CpG site with gene names using a manufacturer-provided mapping ("manifest") file. After selecting genes mapped to DMRs the functional enrichment analysis can be performed using standard tools such as DAVID, GSEA, etc. 

Is this something I could do with `GSEABenchmarkeR`?

**Comment by lgeistlinger** [comment]
Short clarification:

1. If you are interested in analysing a particular microarray / RNA-seq dataset for functional enrichment - eg a case-control study where you are interested in which GO terms / KEGG pathways are enriched for genes showing up in your experimental comparison (and you might wanna try out more than one method for enrichment analysis), - i.e. your primary goal is knowledge gain about the *specific dataset under investigation* - then the `EnrichmentBrowser` is your package to do analysis with. 
 
2. If you have many datasets where you want to compare the performance (runtime, statistical significance, etc) of different enrichment methods - i.e. your primary goal is to *understand methodological aspects and evalutate methods against each other* - then `GSEABenchmarkeR` is the package that you want to use.

That said, I think this is rather an `EnrichmentBrowser` question - as your are interested in a specific dataset where you want to do enrichment analysis for DMRs - and breaks down to a FAQ whether methods can be carried out on simple gene lists, which is answered here:

http://www.bioconductor.org/packages/release/bioc/vignettes/EnrichmentBrowser/inst/doc/EnrichmentBrowser.pdf
(Appendix B Frequently asked questions, _2. Is it possible to apply the EnrichmentBrowser to simple gene lists?_)

In your case of methylation data, it might be additionally worth to consult corresponding GSA implementations that take into account specific characteristics of methylation data:

http://bioconductor.org/packages/missMethyl
http://bioconductor.org/packages/methylGSA
