### ISSUE TITLE
loadEData('geo2kegg') loads list of ExpressionSets

### ISSUE THREAD

**Issue by annikagable** [waldronlab/GSEABenchmarkeR#8]
Not so much an issue as a gotcha.
When using loadEData('geo2kegg') for the first time or with cache = FALSE, a list of ExpressionSets is loaded, although the documentation states that it loads "A list of datasets, typically of class SummarizedExperiment.". This should be made more clear in my opinion, since if then trying to runEA() on an ExpressionSet, it fails.

**Comment by lgeistlinger** [comment]
Yep, as described in the [Vignette, Section 2.1](https://bioconductor.org/packages/release/bioc/vignettes/GSEABenchmarkeR/inst/doc/GSEABenchmarkeR.html#microarray-compendium), `loadEData("geo2kegg", preproc = FALSE)` (default) returns the original microarray probe level data as a list of `ExpressionSet` objects. 

Use `preproc = TRUE` or the `maPreproc` function to summarize the probe level data to gene level data and to obtain a `list` of `SummarizedExperiment` objects.

However, I agree that it doesn't hurt to make this clearer in the documentation of the return type of `loadEData` (done via 68048b8).

Thanks!
